docs: fix the issue of incorrect link pointing to api.md
VictoriaMetrics/operator pull request #783
Opened 2023-10-09 03:26 UTC by hansedong

Fix issue: In README.md, the document referred to by `crd-objects` points to `api.MD`, but the file `api.md` does not exist.

2023-10-09 05:45 UTC, faisalburhanudin commented
hi @hansedong, maybe you can include changes for all markdown links ?

such as
- quick-start.MD
- backups.MD

2023-10-12 02:56 UTC, hansedong commented
@faisalburhanudin 
In the project, I have also found and fixed the issue of incorrect document links referenced elsewhere, please kindly review again.
However, what I need to point out is that there is a reference to `/docs/backups.md` in the `README.md` document. Although I changed `backups.MD` to `backups.md`, I did not find any files related to backups.md in the project. What should this place be changed to?

2023-10-16 01:17 UTC, Haleygo requested changes
Thanks for the fixes, plz see the suggestion.

2023-10-16 01:17 UTC, Haleygo commented on README.md
> + It has integration with VictoriaMetrics `vmbackupmanager` - advanced tools for making backups. Check backup [docs](/docs/backups.md)
```suggestion
 It has integration with VictoriaMetrics [vmbackupmanager](https://docs.victoriametrics.com/vmbackupmanager.html) - advanced tools for making backups. Check [Backup automation for VMSingle](./resources/vmsingle.md#backup-automation) or [Backup automation for VMCluster](./resources/vmcluster.md#backup-automation).```

2023-10-16 02:37 UTC, hansedong commented
@Haleygo Updated, thanks for the suggestion.

2023-10-16 02:38 UTC, Haleygo approved these changes
LGTM!

2023-10-16 02:40 UTC, merged